<?php

return [
  'banner' => 'About Us',
  'item.1.title' => 'We are a local company',
  'item.1.paragraph' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates quas quidem excepturi perferendis eveniet earum ea, eum magni cum, in, consequuntur sit atque quia voluptatem! Nesciunt, nostrum. Deleniti, rem fugiat.Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates quas quidem excepturi perferendis eveniet earum ea, eum magni cum, in, consequuntur sit atque quia voluptatem! Nesciunt, nostrum. Deleniti, rem fugiat.Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates quas quidem excepturi perferendis eveniet earum ea, eum magni cum, in, consequuntur sit atque quia voluptatem! Nesciunt, nostrum. Deleniti, rem fugiat.Lorem ipsum dolor sit amet consectetur adipisicing elit.',
  'item.2.title' => 'With 2 years of experience in the market',
  'item.2.paragraph' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates quas quidem excepturi perferendis eveniet earum ea, eum magni cum, in, consequuntur sit atque quia voluptatem! Nesciunt, nostrum. Deleniti, rem fugiat.Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates quas quidem excepturi perferendis eveniet earum ea, eum magni cum, in, consequuntur sit atque quia voluptatem! Nesciunt, nostrum. Deleniti, rem fugiat.Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates quas quidem excepturi perferendis eveniet earum ea, eum magni cum, in, consequuntur sit atque quia voluptatem! Nesciunt, nostrum. Deleniti, rem fugiat.Lorem ipsum dolor sit amet consectetur adipisicing elit.',
  'item.3.title' => 'Our focus is your satisfaction',
  'item.3.paragraph' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates quas quidem excepturi perferendis eveniet earum ea, eum magni cum, in, consequuntur sit atque quia voluptatem! Nesciunt, nostrum. Deleniti, rem fugiat.Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates quas quidem excepturi perferendis eveniet earum ea, eum magni cum, in, consequuntur sit atque quia voluptatem! Nesciunt, nostrum. Deleniti, rem fugiat.Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates quas quidem excepturi perferendis eveniet earum ea, eum magni cum, in, consequuntur sit atque quia voluptatem! Nesciunt, nostrum. Deleniti, rem fugiat.Lorem ipsum dolor sit amet consectetur adipisicing elit.',
];
