<?php

return [
  'banner' => 'Sobre nós',
  'item.1.title' => 'Somos uma empresa local',
  'item.1.paragraph' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates quas quidem excepturi perferendis eveniet earum ea, eum magni cum, in, consequuntur sit atque quia voluptatem! Nesciunt, nostrum. Deleniti, rem fugiat.Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates quas quidem excepturi perferendis eveniet earum ea, eum magni cum, in, consequuntur sit atque quia voluptatem! Nesciunt, nostrum. Deleniti, rem fugiat.Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates quas quidem excepturi perferendis eveniet earum ea, eum magni cum, in, consequuntur sit atque quia voluptatem! Nesciunt, nostrum. Deleniti, rem fugiat.Lorem ipsum dolor sit amet consectetur adipisicing elit.',
  'item.2.title' => 'Com 2 anos de experiência no mercado',
  'item.2.paragraph' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates quas quidem excepturi perferendis eveniet earum ea, eum magni cum, in, consequuntur sit atque quia voluptatem! Nesciunt, nostrum. Deleniti, rem fugiat.Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates quas quidem excepturi perferendis eveniet earum ea, eum magni cum, in, consequuntur sit atque quia voluptatem! Nesciunt, nostrum. Deleniti, rem fugiat.Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates quas quidem excepturi perferendis eveniet earum ea, eum magni cum, in, consequuntur sit atque quia voluptatem! Nesciunt, nostrum. Deleniti, rem fugiat.Lorem ipsum dolor sit amet consectetur adipisicing elit.',
  'item.3.title' => 'Nosso foco é a sua satisfação',
  'item.3.paragraph' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates quas quidem excepturi perferendis eveniet earum ea, eum magni cum, in, consequuntur sit atque quia voluptatem! Nesciunt, nostrum. Deleniti, rem fugiat.Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates quas quidem excepturi perferendis eveniet earum ea, eum magni cum, in, consequuntur sit atque quia voluptatem! Nesciunt, nostrum. Deleniti, rem fugiat.Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates quas quidem excepturi perferendis eveniet earum ea, eum magni cum, in, consequuntur sit atque quia voluptatem! Nesciunt, nostrum. Deleniti, rem fugiat.Lorem ipsum dolor sit amet consectetur adipisicing elit.',
];
